CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	LOGIN CHARACTER VARYING(25) NOT NULL,
	USER_NAME CHARACTER VARYING(25),
	BIRTHDAY DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_61 ON PUBLIC.USERS (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
	FILM_NAME CHARACTER VARYING(50) NOT NULL,
	DESCRIPTION CHARACTER VARYING(255),
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATING_ID INTEGER,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID)
);

CREATE INDEX IF NOT EXISTS FILMS_RATINGS_FK_INDEX_3 ON PUBLIC.FILMS (RATING_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_3 ON PUBLIC.FILMS (FILM_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.REVIEWS (
	REVIEW_ID BIGINT NOT NULL AUTO_INCREMENT,
	CONTENT CHARACTER VARYING(500) NOT NULL,
	IS_POSITIVE BOOLEAN NOT NULL,
	USER_ID BIGINT NOT NULL,
	FILM_ID BIGINT NOT NULL,
	USEFUL INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT REVIEWS_PK PRIMARY KEY (REVIEW_ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_6 ON PUBLIC.REVIEWS (REVIEW_ID);
CREATE INDEX IF NOT EXISTS REVIEWS_FILMS_FK_INDEX_6 ON PUBLIC.REVIEWS (FILM_ID);
CREATE INDEX IF NOT EXISTS REVIEWS_USERS_FK_INDEX_6 ON PUBLIC.REVIEWS (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.REVIEW_RATINGS (
	REVIEW_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	IS_LIKE BOOLEAN NOT NULL,
	CONSTRAINT REVIEW_RATINGS_PK PRIMARY KEY (REVIEW_ID,USER_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_DA ON PUBLIC.REVIEW_RATINGS (REVIEW_ID,USER_ID);
CREATE INDEX IF NOT EXISTS REVIEW_RATINGS_REVIEWS_FK_INDEX_D ON PUBLIC.REVIEW_RATINGS (REVIEW_ID);
CREATE INDEX IF NOT EXISTS REVIEW_RATINGS_USERS_FK_INDEX_D ON PUBLIC.REVIEW_RATINGS (USER_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FEEDS (
	"TIMESTAMP" TIMESTAMP NOT NULL,
	USER_ID BIGINT NOT NULL,
	EVENT_TYPE CHARACTER VARYING(15) NOT NULL,
	OPERATION CHARACTER VARYING(15) NOT NULL,
	EVENT_ID BIGINT NOT NULL AUTO_INCREMENT,
	ENTITY_ID BIGINT NOT NULL,
	CONSTRAINT FEEDS_PK PRIMARY KEY (EVENT_ID)
);
CREATE INDEX IF NOT EXISTS FEEDS_USERS_FK_INDEX_3 ON PUBLIC.FEEDS (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_3F ON PUBLIC.FEEDS (EVENT_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL PRIMARY KEY,
	GENRE_NAME CHARACTER VARYING(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.MPA_RATINGS (
    RATING_ID INTEGER NOT NULL PRIMARY KEY,
    RATING_NAME CHARACTER VARYING(5) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRES (
	FILM_ID BIGINT NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FILM_GENRES_PK PRIMARY KEY (FILM_ID,GENRE_ID)
);
CREATE INDEX IF NOT EXISTS FILM_GENRES_FILMS_FK_INDEX_C ON PUBLIC.FILM_GENRES (FILM_ID);
CREATE INDEX IF NOT EXISTS FILM_GENRES_GENRES_FK_INDEX_C ON PUBLIC.FILM_GENRES (GENRE_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_C ON PUBLIC.FILM_GENRES (FILM_ID,GENRE_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
	USER_ID BIGINT NOT NULL,
	FILM_ID BIGINT NOT NULL,
	CONSTRAINT LIKES_PK PRIMARY KEY (USER_ID,FILM_ID)
);
CREATE INDEX IF NOT EXISTS LIKES_FILMS_FK_INDEX_4 ON PUBLIC.LIKES (FILM_ID);
CREATE INDEX IF NOT EXISTS LIKES_USERS_FK_INDEX_4 ON PUBLIC.LIKES (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_4 ON PUBLIC.LIKES (USER_ID,FILM_ID);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIPS (
	USER_ID BIGINT NOT NULL,
	FRIEND_ID BIGINT NOT NULL,
	STATUS CHARACTER VARYING(25) DEFAULT 'UNCONFIRMED',
	CONSTRAINT FRIENDSHIPS_PK PRIMARY KEY (FRIEND_ID,USER_ID)
);
CREATE INDEX IF NOT EXISTS FRIENDSHIPS_USERS_FK_2_INDEX_D ON PUBLIC.FRIENDSHIPS (FRIEND_ID);
CREATE INDEX IF NOT EXISTS FRIENDSHIPS_USERS_FK_INDEX_D ON PUBLIC.FRIENDSHIPS (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS PRIMARY_KEY_D ON PUBLIC.FRIENDSHIPS (USER_ID,FRIEND_ID);


-- внешние включи

-- FILMS -> MPA_RATINGS
ALTER TABLE PUBLIC.FILMS DROP CONSTRAINT IF EXISTS FILMS_MPA_RATINGS_FK;
ALTER TABLE PUBLIC.FILMS ADD CONSTRAINT FILMS_MPA_RATINGS_FK
    FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.MPA_RATINGS(RATING_ID);

-- FILM_GENRES -> FILMS
ALTER TABLE PUBLIC.FILM_GENRES DROP CONSTRAINT IF EXISTS FILM_GENRES_FILMS_FK;
ALTER TABLE PUBLIC.FILM_GENRES ADD CONSTRAINT FILM_GENRES_FILMS_FK
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- FILM_GENRES -> GENRES
ALTER TABLE PUBLIC.FILM_GENRES DROP CONSTRAINT IF EXISTS FILM_GENRES_GENRES_FK;
ALTER TABLE PUBLIC.FILM_GENRES ADD CONSTRAINT FILM_GENRES_GENRES_FK
    FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- LIKES -> FILMS
ALTER TABLE PUBLIC.LIKES DROP CONSTRAINT IF EXISTS LIKES_FILMS_FK;
ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_FILMS_FK
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- LIKES -> USERS
ALTER TABLE PUBLIC.LIKES DROP CONSTRAINT IF EXISTS LIKES_USERS_FK;
ALTER TABLE PUBLIC.LIKES ADD CONSTRAINT LIKES_USERS_FK
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- FRIENDSHIPS -> USERS (user_id)
ALTER TABLE PUBLIC.FRIENDSHIPS DROP CONSTRAINT IF EXISTS FRIENDSHIPS_USERS_FK;
ALTER TABLE PUBLIC.FRIENDSHIPS ADD CONSTRAINT FRIENDSHIPS_USERS_FK
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- FRIENDSHIPS -> USERS (friend_id)
ALTER TABLE PUBLIC.FRIENDSHIPS DROP CONSTRAINT IF EXISTS FRIENDSHIPS_USERS_FK_2;
ALTER TABLE PUBLIC.FRIENDSHIPS ADD CONSTRAINT FRIENDSHIPS_USERS_FK_2
    FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(USER_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- REVIEWS -> FILMS
ALTER TABLE PUBLIC.REVIEWS DROP CONSTRAINT IF EXISTS REVIEWS_FILMS_FK;
ALTER TABLE PUBLIC.REVIEWS ADD CONSTRAINT REVIEWS_FILMS_FK
    FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- REVIEWS -> USERS
ALTER TABLE PUBLIC.REVIEWS DROP CONSTRAINT IF EXISTS REVIEWS_USERS_FK;
ALTER TABLE PUBLIC.REVIEWS ADD CONSTRAINT REVIEWS_USERS_FK
    FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
    ON DELETE RESTRICT ON UPDATE RESTRICT;

-- REVIEW_RATINGS -> REVIEWS
ALTER TABLE PUBLIC.REVIEW_RATINGS DROP CONSTRAINT IF EXISTS REVIEW_RATINGS_REVIEWS_FK;
ALTER TABLE PUBLIC.REVIEW_RATINGS ADD CONSTRAINT REVIEW_RATINGS_REVIEWS_FK
FOREIGN KEY (REVIEW_ID) REFERENCES PUBLIC.REVIEWS(REVIEW_ID)
ON DELETE RESTRICT ON UPDATE RESTRICT;

-- REVIEW_RATINGS -> USERS
ALTER TABLE PUBLIC.REVIEW_RATINGS DROP CONSTRAINT IF EXISTS REVIEW_RATINGS_USERS_FK;
ALTER TABLE PUBLIC.REVIEW_RATINGS ADD CONSTRAINT REVIEW_RATINGS_USERS_FK
FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
ON DELETE RESTRICT ON UPDATE RESTRICT;

-- FEEDS -> USERS
ALTER TABLE PUBLIC.FEEDS DROP CONSTRAINT IF EXISTS FEEDS_USERS_FK;
ALTER TABLE PUBLIC.FEEDS ADD CONSTRAINT FEEDS_USERS_FK FOREIGN KEY (USER_ID)
REFERENCES PUBLIC.USERS(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;